library/books/urls.py
from django.contrib import admin
from django.urls import path
from books import views



app_name = 'books'
urlpatterns = [
    path('',views.home.as_view(), name='home'),
    path('viewbooks',views.viewbooks.as_view(), name='viewbooks'),
    path('addbooks',views.addbooks.as_view(), name='addbooks'),
    path('detail/<int:i>',views.Detailview.as_view(), name='detail'),
    path('delete/<int:i>',views.Deleteview.as_view(), name='delete'),
    path('edit/<int:i>',views.Editview.as_view(), name='edit'),
]

from django.conf.urls.static import static
from django.conf import settings

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

library/library/urls.py
from django.contrib import admin
from django.urls import path,include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls')),
    path('user/',include('user.urls')),
]

library/user/urls.py
from django.contrib import admin
from django.urls import path
from user import views
app_name = 'user'
urlpatterns = [
    path('register',views.register.as_view(), name='register'),
    path('userlogin',views.Userlogin.as_view(), name='userlogin'),
    path('userlogout',views.Userlogout.as_view(), name='userlogout'),

]

library/books/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=30)
    author = models.CharField(max_length=30)
    price=models.IntegerField()
    pages=models.IntegerField()
    image=models.ImageField(upload_to="images")
    language = models.CharField(max_length=30)

library/user/models.py
from django.db import models

# Create your models here.

library/books/forms.py
from django import forms

from books.models import Book


# class addbooksform(forms.Form):
#     Title=forms.CharField()
#     Author=forms.CharField()
#     Price=forms.IntegerField()
#     Pages=forms.IntegerField()
#     Language=forms.CharField()

class addbooksform(forms.ModelForm): #define the form based on book model

    class Meta:  #innerclass used to define the structure of form.
        model = Book
        fields='__all__'

library/user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm




class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1','password2', 'email', 'first_name', 'last_name']

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

library/books/views.py
from idlelib.textview import ViewFrame

from django.shortcuts import render,redirect
from books.forms import addbooksform
from django.views import View


# Create your views here.
# def home(request):
#     return render(request, 'home.html')
# def addbooks(request):
#     return render(request, 'addbooks.html')
# def viewbooks(request):
#     return render(request, 'viewbooks.html')

class home(View):
    def get(self, request):
        return render(request, 'home.html')

class viewbooks(View):

    def get(self, request):
        b=Book.objects.all()
        context = {'books':b}
        return render(request, 'viewbooks.html',context)


from books.models import Book

class addbooks(View):
    def get(self, request):
        form_instance = addbooksform()
        context = {'form':form_instance}
        return render(request, 'addbooks.html',context)

    def post(self,request):
        #craeting from object using submitted data
        form_instance=addbooksform(request.POST,request.FILES)
        #check whether data is valid or not
        if form_instance.is_valid():

            #process the data after validation
            # data=form_instance.cleaned_data
            # # print('cleaned data',data)
            # t=data['title']
            # a=data['author']
            # p=data['price']
            # pg=data['page']
            # l=data['language']
            # b=Book.objects.create(title=t,author=a,price=p,page=pg,language=l)
            # b.save()
            form_instance.save()
        return render(request,'addbooks.html')

class Detailview(View):
    def get(self, request,i):
        b=Book.objects.get(id=i)
        context = {'book':b}
        return render(request, 'detail.html',context)

class Deleteview(View):
    def get(self, request,i):
        b=Book.objects.get(id=i)
        b.delete()
        return redirect('books:viewbooks')

class Editview(View):
    def post(self, request,i):
        b=Book.objects.get(id=i)
        form_instance = addbooksform(request.POST, request.FILES,instance=b)
        if form_instance.is_valid():
            form_instance.save()
        return redirect('books:addbooks')


    def get(self, request,i):
        b=Book.objects.get(id=i)
        from_instance=addbooksform(instance=b)
        context = {'form':from_instance}
        return render(request, 'edit.html',context)

library/user/views.py
from django.shortcuts import render,redirect
from django.views import View

from user.forms import SignupForm
from django.contrib.auth import authenticate,login

# Create your views here.
# def register(request):
#     return render(request, "register.html")
# def login(request):
#     return render(request,"login.html")

class register(View):
    def post(self,request):
        form_instance = SignupForm(request.POST)
        if form_instance.is_valid():
            form_instance.save()
            return redirect('user:userlogin')


    def get(self, request):
        form_instance=SignupForm()
        context={'form':form_instance}
        return render(request, 'register.html',context)

from user.forms import LoginForm
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
class Userlogin(View):
    def post(self,request):
       form_instance = LoginForm(request.POST)
       if form_instance.is_valid():
        data = form_instance.cleaned_data
        u = data['username']
        p = data['password']
        user = authenticate(username=u, password=p)

        if user:  # if user exists
            login(request, user)  # adds the user into current sessions
            return redirect('books:home')
        else:  # if user does not exist
            messages.error(request, "Invalid credentials.")
            return redirect('user:userlogin')

    def get(self, request):
        form_instance = LoginForm()
        context={'form':form_instance}
        return render(request, 'login.html', context)

class Userlogout(View):
    def get(self, request):
        logout(request)   #remove the user from the  current session
        return redirect('user:userlogin')

library/templates/addbooks.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags%}
<div class="container mt-3 p-6 w-50 border border-2 border-light">
<h3 class="text-center">Add Books</h3>
   <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit">
    </form>
</div>
    {% endblock %}

library/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body class="bg-warning">
<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <div class="container">
    <a class="navbar-brand fw-bold fst-italic fs-2" href="#">Library</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 fw-bold fs-5 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'books:home' %}">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:viewbooks' %}">ViewBooks</a>
        </li>
              <li class="nav-item">
          <a class="nav-link" href="{% url 'books:addbooks' %}">AddBooks</a>
        </li>

                     <li class="nav-item">
          <a class="nav-link" href="{% url 'user:userlogout' %}">Logout</a>
        </li>
        {% else %}

                  <li class="nav-item">
          <a class="nav-link" href="{% url 'user:register' %}">Register</a>
        </li>
                    <li class="nav-item">
          <a class="nav-link" href="{% url 'user:userlogin' %}">Login</a>
        </li>
        {% endif %}


      </ul>
      <form class="d-flex justify-content-end">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-dark" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}
<h1>Home</h1>
{% endblock %}





</body>
</html>

library/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5 p-5 border border-2 shadow">
  <h3 class="text-center mt-3">Book Details</h3>
<!--{{book.title}}-->
<!--{{book.author}}-->
<!--{{book.page}}-->
<!--{{book.price}}-->
<!--{{book.image}}-->
<table class="table table-bordered">
  <tr>
    <th>Title</th>
    <td>{{book.title}}</td>
  </tr>
  <tr>
    <th>Author</th>
    <td>{{book.author}}</td>
  </tr>
  <tr>
    <th>Price</th>
    <td>{{book.price}}</td>
  </tr>
  <tr>
    <th>Pages</th>
    <td>{{book.pages}}</td>
  </tr>
  <tr>
    <th>Image</th>
    <td><img src="{{book.image.url}}" height="200px" width="200px"</td>
  </tr>
</table>
  </div>




{% endblock %}

library/templates/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags%}
{% block content %}
{{book}}
<h3 class="text-center mt-3">Edit Book Details</h3>
<div class="container mt-3 p-6 w-50 border border-2 border-light">
 <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit">
    </form>
</div>
{% endblock %}

library/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h3 class="text-center">Welcome to Library</h3>

  <form method="post">
        {% csrf_token %}

<!--        <input type="submit">-->
    </form>
{% endblock %}

library/templates/login.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container w-75 p-5 mt-5 border border-2 fst-italic text-center">
    <h3>login</h3>
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="mb-3">
      <input type="submit" class="btn btn-dark">
    </div>
  </form>
    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li type="none" class="text-danger"> {{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

</div>
{% endblock %}
</html>

library/templates/register.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container w-50 p-5 mt-5 border border-2 fst-italic text-center">
    <h3>Register</h3>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="mb-3">
            <input type="submit" class="btn btn-dark" value="Register">
        </div>
    </form>
</div>
{% endblock %}
</html>

library/templates/viewbooks.html
{% extends 'base.html' %}

{% block content %}
<h3 class="text-center">View books</h3>
<!--{% for i in books %}-->


<!--{{i.title}}{{i.author}}{{i.price}}{{i.pages}}{{i.language}}<br>-->
<!--{% endfor %}-->


<table class="table table-bordered">
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Price</th>
    <th>Pages</th>
    <th>Image</th>
    <th>Language</th>
    <th>Actions</th>
  </tr>
  {% for i in books %}
  <tr>
    <td>{{i.title}}</td>
    <td>{{i.author}}</td>
    <td>{{i.price}}</td>
    <td>{{i.pages}}</td>
    <td><img src="{{i.image.url}}" height="100px" width="100px"></td>
    <td>{{i.language}}</td>
    <td><a class="btn btn-danger" href="{% url 'books:detail' i.id %}">Details</a>
    <a class="btn btn-danger"href="{% url 'books:edit' i.id %}">Edit</a>
    <a class="btn btn-danger" href="{% url 'books:delete' i.id %}">Delete</a></td>

  </tr>
  {% endfor %}
</table>


{% endblock %}